[2024-08-01T07:55:58.767+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscraping.Post-Scrape_script manual__2024-07-18T01:40:54.041901+00:00 [queued]>
[2024-08-01T07:55:58.780+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscraping.Post-Scrape_script manual__2024-07-18T01:40:54.041901+00:00 [queued]>
[2024-08-01T07:55:58.780+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 3
[2024-08-01T07:55:58.796+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Post-Scrape_script> on 2024-07-18 01:40:54.041901+00:00
[2024-08-01T07:55:58.801+0000] {standard_task_runner.py:60} INFO - Started process 3686 to run task
[2024-08-01T07:55:58.805+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Webscraping', 'Post-Scrape_script', 'manual__2024-07-18T01:40:54.041901+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/webscrape_dag.py', '--cfg-path', '/tmp/tmptnvvnabp']
[2024-08-01T07:55:58.806+0000] {standard_task_runner.py:88} INFO - Job 232: Subtask Post-Scrape_script
[2024-08-01T07:55:58.856+0000] {task_command.py:423} INFO - Running <TaskInstance: Webscraping.Post-Scrape_script manual__2024-07-18T01:40:54.041901+00:00 [running]> on host 8227a508e5ed
[2024-08-01T07:55:58.947+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Webscraping' AIRFLOW_CTX_TASK_ID='Post-Scrape_script' AIRFLOW_CTX_EXECUTION_DATE='2024-07-18T01:40:54.041901+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-18T01:40:54.041901+00:00'
[2024-08-01T07:55:58.948+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-01T07:55:58.948+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/post_scrape.py']
[2024-08-01T07:55:58.957+0000] {subprocess.py:86} INFO - Output:
[2024-08-01T07:55:58.979+0000] {subprocess.py:93} INFO - python3: can't open file '/opt/***/post_scrape.py': [Errno 2] No such file or directory
[2024-08-01T07:55:58.984+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-08-01T07:55:58.995+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-08-01T07:55:58.999+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscraping, task_id=Post-Scrape_script, execution_date=20240718T014054, start_date=20240801T075558, end_date=20240801T075558
[2024-08-01T07:55:59.012+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 232 for task Post-Scrape_script (Bash command failed. The command returned a non-zero exit code 2.; 3686)
[2024-08-01T07:55:59.058+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-08-01T07:55:59.073+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
