[2024-07-16T07:42:28.918+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-16T07:42:26.517176+00:00 [queued]>
[2024-07-16T07:42:28.929+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-16T07:42:26.517176+00:00 [queued]>
[2024-07-16T07:42:28.930+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-07-16T07:42:28.942+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): Pre-Scrape_script> on 2024-07-16 07:42:26.517176+00:00
[2024-07-16T07:42:28.946+0000] {standard_task_runner.py:60} INFO - Started process 71 to run task
[2024-07-16T07:42:28.951+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Webscraping', 'Pre-Scrape_script', 'manual__2024-07-16T07:42:26.517176+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/webscrape_dag.py', '--cfg-path', '/tmp/tmpfc9mum5t']
[2024-07-16T07:42:28.952+0000] {standard_task_runner.py:88} INFO - Job 85: Subtask Pre-Scrape_script
[2024-07-16T07:42:29.000+0000] {task_command.py:423} INFO - Running <TaskInstance: Webscraping.Pre-Scrape_script manual__2024-07-16T07:42:26.517176+00:00 [running]> on host 0d386e3ce452
[2024-07-16T07:42:29.113+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Webscraping' AIRFLOW_CTX_TASK_ID='Pre-Scrape_script' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T07:42:26.517176+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T07:42:26.517176+00:00'
[2024-07-16T07:42:29.115+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-16T07:42:29.117+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/ec2-user/pre_scrape.py']
[2024-07-16T07:42:29.131+0000] {subprocess.py:86} INFO - Output:
[2024-07-16T07:42:29.156+0000] {subprocess.py:93} INFO - python3: can't open file '/home/ec2-user/pre_scrape.py': [Errno 2] No such file or directory
[2024-07-16T07:42:29.158+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-07-16T07:42:29.175+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-07-16T07:42:29.177+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Webscraping, task_id=Pre-Scrape_script, execution_date=20240716T074226, start_date=20240716T074228, end_date=20240716T074229
[2024-07-16T07:42:29.192+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 85 for task Pre-Scrape_script (Bash command failed. The command returned a non-zero exit code 2.; 71)
[2024-07-16T07:42:29.204+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T07:42:29.229+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
